<?xml version="1.0" encoding="utf-8"?><Database Name="ClimbingGyms" Class="GymDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-83BJHBD\SQLEXPRESS01;Initial Catalog=ClimbingGyms;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="ClimbingGym.Data.Properties.Settings" SettingsPropertyName="ClimbingGymsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Gyms" Member="Gyms">
    <Type Name="Gym">
      <Column Name="GymID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>